name: Send to Production

on: 
  workflow_dispatch:
  
jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      
      - name: Merge code
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'production'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
